In [ ]:
import pandas as pd
import numpy as np

# Raw e-commerce data with missing values (np.nan)
data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'],
    'Price': [1200.0, 25.0, np.nan, 300.0, 80.0],
    'Quantity_Sold': [15, 120, 45, np.nan, 60]
}

df = pd.DataFrame(data)
print("--- Raw Data ---")
print(df)

df['Price'] = df['Price'].fillna(df['Price'].median())
df['Quantity_Sold'] = df['Quantity_Sold'].fillna(0)

array = np.array([df['Price'],df['Quantity_Sold']])

revenue_data = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones'], 
    'Revenue': array[0] * array[1, :]
}
total_revnue = pd.DataFrame(revenue_data)
print("--- Filled Data ---")
print(df)
print("--- Math ---")
print(f"{array} \n")
print(array[0] * array[1, :])
print("--- Result ---")
print(total_revnue)

--- Raw Data ---
      Product   Price  Quantity_Sold
0      Laptop  1200.0           15.0
1       Mouse    25.0          120.0
2    Keyboard     NaN           45.0
3     Monitor   300.0            NaN
4  Headphones    80.0           60.0
--- Filled Data ---
      Product   Price  Quantity_Sold
0      Laptop  1200.0           15.0
1       Mouse    25.0          120.0
2    Keyboard   190.0           45.0
3     Monitor   300.0            0.0
4  Headphones    80.0           60.0
--- Math ---
[[1200.   25.  190.  300.   80.]
 [  15.  120.   45.    0.   60.]] 

[18000.  3000.  8550.     0.  4800.]
--- Result ---
      Product  Revenue
0      Laptop  18000.0
1       Mouse   3000.0
2    Keyboard   8550.0
3     Monitor      0.0
4  Headphones   4800.0


In [ ]:
import numpy as np
import pandas as pd

array = np.array([1, 2, 3])
?array